[auth]
user_agent = "example_email@email_domain.com"

[keys]
finnhub = ""
mexc = ""

[server]
host = "localhost"
port = "5432:5432"

[database]
name = "postgres"
username = "postgres"
password = "postgres"

