[auth]
user_agent = "kimonvostanis@gmail.com"

[keys]
finnhub = "ck5v6l9r01qls0umdfugck5v6l9r01qls0umdfv0"
mexc = ""

[server]
host = "localhost"
port = "5432"

[database]
name = "postgres"
username = "postgres"
password = "postgres"

