version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sec-api
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
